
import React from 'react';
import Image from 'next/image';
import { Share2, Heart, MessageCircle, Repeat2, Users } from 'lucide-react';

const SocialViralSection: React.FC = () => {
  return (
    <section className="py-24 bg-zinc-950">
      <div className="container mx-auto px-4">
        <div className="flex flex-col lg:flex-row items-center gap-16">
          <div className="w-full lg:w-1/2 order-2 lg:order-1">
            <div className="relative group">
               {/* Mock Social Posts */}
               <div className="absolute -top-10 -left-10 w-64 p-4 bg-white rounded-xl shadow-2xl transform -rotate-6 z-20 hidden md:block">
                 <div className="flex items-center gap-2 mb-3">
                   <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center">
                     <Share2 className="w-4 h-4 text-blue-600" />
                   </div>
                   <div className="text-xs font-bold text-black">@FTBL_Daily</div>
                 </div>
                 <div className="w-full h-32 bg-zinc-100 rounded-lg mb-2 overflow-hidden">
                    <Image src="https://picsum.photos/seed/social1/300/200" alt="Social post preview" width={300} height={200} className="w-full h-full object-cover" />
                 </div>
                 <div className="text-[10px] text-zinc-600 font-medium">My All-Time Prem XI. What we thinking? 🔥</div>
               </div>

               <div className="absolute -bottom-10 -right-10 w-64 p-4 bg-black border border-zinc-800 rounded-xl shadow-2xl transform rotate-3 z-20 hidden md:block">
                 <div className="flex items-center justify-between mb-3">
                   <div className="flex items-center gap-2">
                     <div className="w-6 h-6 rounded-full bg-green-500"></div>
                     <span className="text-[10px] font-bold">DraftMaster_Official</span>
                   </div>
                   <div className="px-2 py-0.5 bg-green-500 text-[8px] font-bold text-black rounded uppercase tracking-tighter">NEW CHALLENGE</div>
                 </div>
                 <div className="w-full h-24 bg-zinc-900 rounded mb-2"></div>
                 <div className="flex gap-4">
                   <Heart className="w-4 h-4 text-red-500" />
                   <MessageCircle className="w-4 h-4 text-zinc-500" />
                   <Repeat2 className="w-4 h-4 text-zinc-500" />
                 </div>
               </div>

              <div className="relative w-full aspect-square md:aspect-video rounded-3xl overflow-hidden shadow-2xl">
                <Image
                  src="https://picsum.photos/seed/football/1200/800"
                  alt="Viral social shares"
                  fill
                  sizes="(max-width: 1024px) 100vw, 50vw"
                  className="object-cover brightness-50"
                />
                <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center p-8 bg-black/40 backdrop-blur-md rounded-2xl border border-white/10 max-w-sm">
                      <h4 className="text-2xl font-black mb-2">10M+ IMPRESSIONS</h4>
                      <p className="text-sm text-zinc-300">Generated by users sharing their lineups last week alone.</p>
                    </div>
                 </div>
               </div>
            </div>
          </div>

          <div className="w-full lg:w-1/2 order-1 lg:order-2">
            <h2 className="text-4xl md:text-6xl font-black mb-8">BUILT TO GO VIRAL</h2>
            <p className="text-zinc-400 text-xl leading-relaxed mb-8">
              Football creators spend hours on Canva making squad graphics. 
              DraftMaster FC turns a 2-hour job into a 2-minute masterpiece. 
            </p>
            <ul className="space-y-6">
              <li className="flex gap-4">
                <div className="w-12 h-12 rounded-full bg-green-500/10 flex-shrink-0 flex items-center justify-center text-green-500">
                  <Share2 className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-xl font-bold mb-1">One-Tap Social Export</h4>
                  <p className="text-zinc-500 text-sm">Pre-formatted for X, Instagram, TikTok, and Reddit.</p>
                </div>
              </li>
              <li className="flex gap-4">
                <div className="w-12 h-12 rounded-full bg-green-500/10 flex-shrink-0 flex items-center justify-center text-green-500">
                  <Heart className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-xl font-bold mb-1">Community Voting</h4>
                  <p className="text-zinc-500 text-sm">Get your squad to the top of the "Trending" feed.</p>
                </div>
              </li>
              <li className="flex gap-4">
                <div className="w-12 h-12 rounded-full bg-green-500/10 flex-shrink-0 flex items-center justify-center text-green-500">
                  <Users className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-xl font-bold mb-1">Club-Based Communities</h4>
                  <p className="text-zinc-500 text-sm">Argue with fellow fans in dedicated club zones.</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SocialViralSection;
